### PR TITLE
cmd/check-copyright: new command to check presence of copyright headers in Go files

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

Updates gonum/gonum#537.

### CODE REVIEW

**Comment by btracey** [comment]
Does our current code pass the test? I feel like it might not and that it's probably my fault, so I could hunt for the original commits.

**Comment by kortschak** [comment]
It does depending on the regexp. The only package that doesn't with a regexp that matches the common form is floats which lacks the "©".

**Comment by kortschak** [comment]
```
$ check-copyright -notice "Copyright ©20[0-9]{2} The Gonum Authors\. All rights reserved\."
blas/gonum/level1doubleBench_auto_test.go
blas/testblas/benchautogen/autogen_bench_level1double.go
floats/examples_test.go
floats/floats.go
floats/floats_test.go
graph/formats/dot/internal/paste_copyright.go
```

We can do multiline checks to make sure the entire header is intact, but there are a few files that have our copyright as a single line, for example mathext/internal/cephes, so I think just the single line above is best.

**Review by sbinet — APPROVED** [review]

**Comment by sbinet** [comment]
ah, perhaps add it to this repo as part of `.travis.yml` ?

**Comment by kortschak** [comment]
That would be part 2.

**Pull request merged**
