### PR TITLE
Autodiff

### LINKED ISSUE #1268: diff/autofd: package to generate derivative code from a Go func
### Background

see #1265 

### Proposal

introduce a `diff/autofd` package to automatically generate the derivative's code from a `func` declaration.

```go
package autofd

type Func struct {
	Path  string // import path of the package holding the function
	Name  string // function or method name
	Deriv string // name of the output derivative function
}

// Derivative generates the derivative code from the given function declaration.
func Derivative(w io.Writer, f Func) error { ... }
```

### Potential impact of proposal

we could also consider creating an `autofd` command leveraging that function to generate code from the command line:
```
$> autofd -pkg gonum.org/v1/gonum/diff/autofd/internal/testfunc -fct F1
func DerivF1(x float64) float64 {
	return dual.Mul(dual.Number{Real:x, Emag:1}, dual.Number{Real:x, Emag:1}).Emag
}
```

another possible work item would be to leverage [expreduce](https://github.com/corywalker/expreduce).

### PR DESCRIPTION
**Pull request by sbinet**
Please take a look.

Fixes gonum/gonum#1268

### CODE REVIEW

**Comment by sbinet** [comment]
note I fixed a bug I noticed _wrt_ the handling of identifiers that are constants _wrt_ the derivative.

**Comment by kortschak** [comment]
Can you point to the change?

**Comment by sbinet** [comment]
sure:

https://github.com/gonum/tools/blob/18476c62c70bc273e9f63fcd80f281eb2738994e/autofd/autofd.go#L224..L235

**Comment by sbinet** [comment]
it used to be:
https://github.com/sbinet-gonum/gonum/blob/213364c99b327b26bcf51b188ede38ceb02189e6/diff/autofd/autofd.go#L228..L234

**Comment by kortschak** [comment]
I'm sorry, it's been a while since I did this. Can you explain the change.

**Comment by sbinet** [comment]
before the change, `autofd.Derivative` would have handled:

```go
var pi = math.Pi
func F9(x float64) float64 {
	return pi * x
}
```

like so:
```go
func DerivF9(x float64) float64 {
	v := dual.Mul(dual.Number{Real:pi, Emag:1}, dual.Number{Real:x, Emag:1})
	return v.Emag
}
```

instead of (IIRC the derivative rules _wrt_ `x` and IIUC how `dual` and `hyperdual` work):
```go
func DerivF9(x float64) float64 {
	v := dual.Mul(dual.Number{Real:pi}, dual.Number{Real:x, Emag:1})
	return v.Emag
}
```

**Comment by sbinet** [comment]
see for example:
https://play.golang.org/p/vPYt0W9I5Qh

**Comment by kortschak** [comment]
Thanks

**Review by kortschak — DISMISSED** [review]

**Comment by sbinet** [comment]
(latest push was just a rebase+squash of some commits. no code change)

**Pull request merged**
